In [2]:
import pandas as pd
# pd.set_option("display.max_rows", None, "display.max_columns", None)

In [34]:
emmy_df= pd.read_csv('emmys.csv').dropna()
stream_df = pd.read_csv('streaming platforms.csv').dropna()
stream_df

,Unnamed: 0,ID,,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Directors,Genres,Country,Language,Runtime
0,0,1,Inception,2010,13+,8.8,87%,1,0,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,1,2,The Matrix,1999,18+,8.7,87%,1,0,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,2,3,Avengers: Infinity War,2018,13+,8.5,84%,1,0,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,3,4,Back to the Future,1985,7+,8.5,96%,1,0,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,97%,1,0,1,0,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16657,16657,16658,A Kid in King Arthur's Court,1995,7+,4.7,5%,0,0,0,1,0,Michael Gottlieb,"Adventure,Comedy,Family,Fantasy,Romance","United States,Hungary,United Kingdom",English,89.0
16671,16671,16672,George of the Jungle 2,2003,7+,3.3,17%,0,0,0,1,0,David Grossman,"Adventure,Comedy,Family","United States,Australia",English,87.0
16677,16677,16678,That Darn Cat,1997,7+,4.7,13%,0,0,0,1,0,Robert Stevenson,"Comedy,Crime,Family,Thriller",United States,"English,French",116.0
16687,16687,16688,Kazaam,1996,7+,3.0,6%,0,0,0,1,0,Paul Michael Glaser,"Comedy,Family,Fantasy,Musical",United States,English,93.0
16705,16705,16706,Meet the Deedles,1998,7+,4.1,7%,0,0,0,1,0,Steve Boyum,"Comedy,Family",United States,English,93.0

In [50]:
stream_clean = stream_df.rename(columns = {'                                                         ' : 'nominee', 'Year': 'year'})

In [38]:
age = stream_clean['Age']

In [51]:
IMDB = stream_clean['IMDb']

In [52]:
nominee = stream_clean['nominee']

In [41]:
rotten_tomatoes = stream_clean['Rotten Tomatoes']

In [64]:
year = stream_clean['year']

In [65]:
rating = {
    "nominee":nominee,
    "Age": age,
    "IMDB": IMDB,
    "Rotten Tomatoes": rotten_tomatoes,
    "year" : year
}

In [66]:
rating_df = pd.DataFrame(rating)
rating_df

                              nominee  Age  IMDB Rotten Tomatoes  year
0                           Inception  13+   8.8             87%  2010
1                          The Matrix  18+   8.7             87%  1999
2              Avengers: Infinity War  13+   8.5             84%  2018
3                  Back to the Future   7+   8.5             96%  1985
4      The Good, the Bad and the Ugly  18+   8.8             97%  1966
...                               ...  ...   ...             ...   ...
16657    A Kid in King Arthur's Court   7+   4.7              5%  1995
16671          George of the Jungle 2   7+   3.3             17%  2003
16677                   That Darn Cat   7+   4.7             13%  1997
16687                          Kazaam   7+   3.0              6%  1996
16705                Meet the Deedles   7+   4.1              7%  1998

[3301 rows x 5 columns]

In [55]:
stream_clean = stream_df.rename(columns = {'Title' : 'nominee', 'Year': 'year'})
# stream_clean['nominee'] = stream_clean['nominee'].str.lower()
# emmy_df['nominee'] = emmy_df['nominee'].str.lower()

In [28]:
netflix =  emmy_df.loc[emmy_df['detail'] == 'Netflix']

In [29]:
hulu =   emmy_df.loc[emmy_df['detail'] == 'Hulu']

In [30]:
amazon = emmy_df.loc[emmy_df['detail'] == 'Amazon']

In [33]:
streaming = pd.concat([hulu, amazon, netflix])
streaming

,year,category,winner,nominee,detail
18262,2016,Outstanding Writing For A Variety Special,0,Triumph's Election Special 2016,Hulu
18553,2016,Outstanding Special Visual Effects In A Suppor...,0,"11.22.63 - ""The Rabbit Hole""",Hulu
18736,2017,Outstanding Directing For A Drama Series,1,"The Handmaid's Tale - ""Offred (Pilot)""",Hulu
18737,2017,Outstanding Directing For A Drama Series,0,"The Handmaid's Tale - ""The Bridge""",Hulu
18752,2017,Outstanding Drama Series,1,The Handmaid's Tale,Hulu
...,...,...,...,...,...
19163,2017,Outstanding Motion Design,1,13th,Netflix
19208,2017,Outstanding Creative Achievement In Interactiv...,0,Stranger Things VR Experience,Netflix
19222,2017,Outstanding Music Supervision,0,"Master Of None - ""Amarsi Un Po""",Netflix
19223,2017,Outstanding Music Supervision,0,"Stranger Things - ""Chapter Two: The Weirdo On ...",Netflix
19234,2017,"Outstanding Production Design For Variety, Non...",0,"Bill Nye Saves The World - ""Earth Is A Hot Mess""",Netflix

In [68]:
emmy_streaming_df = pd.merge(rating_df, streaming, on="year", how="left")
emmy_streaming_df

,nominee_x,Age,IMDB,Rotten Tomatoes,year,category,winner,nominee_y,detail
0,Inception,13+,8.8,87%,2010,NaN,NaN,NaN,NaN
1,The Matrix,18+,8.7,87%,1999,NaN,NaN,NaN,NaN
2,Avengers: Infinity War,13+,8.5,84%,2018,NaN,NaN,NaN,NaN
3,Back to the Future,7+,8.5,96%,1985,NaN,NaN,NaN,NaN
4,"The Good, the Bad and the Ugly",18+,8.8,97%,1966,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
46644,A Kid in King Arthur's Court,7+,4.7,5%,1995,NaN,NaN,NaN,NaN
46645,George of the Jungle 2,7+,3.3,17%,2003,NaN,NaN,NaN,NaN
46646,That Darn Cat,7+,4.7,13%,1997,NaN,NaN,NaN,NaN
46647,Kazaam,7+,3.0,6%,1996,NaN,NaN,NaN,NaN
46648,Meet the Deedles,7+,4.1,7%,1998,NaN,NaN,NaN,NaN

In [61]:
# emmy_streaming_df.dropna(subset=['detail'])
netflix_emmy_streaming = emmy_streaming_df.loc[emmy_streaming_df['detail'] == 'Netflix']

,nominee,Age,IMDB,Rotten Tomatoes,year,category,winner,detail
83,13th,18+,8.2,96%,2017.0,Outstanding Documentary Or Nonfiction Special,1.0,Netflix
84,13th,18+,8.2,96%,2017.0,Outstanding Picture Editing For A Nonfiction P...,0.0,Netflix
85,13th,18+,8.2,96%,2017.0,Outstanding Sound Editing For A Nonfiction Pro...,0.0,Netflix
86,13th,18+,8.2,96%,2017.0,Outstanding Directing For A Nonfiction Program,0.0,Netflix
87,13th,18+,8.2,96%,2017.0,Outstanding Writing For A Nonfiction Program,1.0,Netflix
88,13th,18+,8.2,96%,2017.0,Outstanding Motion Design,1.0,Netflix
229,The White Helmets,16+,7.5,100%,2017.0,Outstanding Music Composition For A Limited Se...,0.0,Netflix
230,The White Helmets,16+,7.5,100%,2017.0,Exceptional Merit In Documentary Filmmaking,0.0,Netflix
272,Louis C.K. 2017,18+,7.6,100%,2017.0,Outstanding Variety Special,0.0,Netflix
273,Louis C.K. 2017,18+,7.6,100%,2017.0,Outstanding Writing For A Variety Special,0.0,Netflix
669,Amanda Knox,18+,6.9,87%,2017.0,Outstanding Documentary Or Nonfiction Special,0.0,Netflix
670,Amanda Knox,18+,6.9,87%,2017.0,Outstanding Writing For A Nonfiction Program,0.0,Netflix
747,A Very Murray Christmas,18+,5.5,71%,2016.0,Outstanding Television Movie,0.0,Netflix
748,A Very Murray Christmas,18+,5.5,71%,2016.0,Outstanding Music Direction,0.0,Netflix

In [63]:
hulu_emmy_streaming = emmy_streaming_df.loc[emmy_streaming_df['detail'] == 'Hulu']
hulu_emmy_streaming

Empty DataFrame
Columns: [nominee, Age, IMDB, Rotten Tomatoes, year, category, winner, detail]
Index: []

In [69]:
len(netflix)

157